version: '3.8'

services:
  # Laravel Application
  app:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: corevsphim_app
    restart: unless-stopped
    working_dir: /var/www/html
    deploy:
      resources:
        limits:
          cpus: '0.8'      # Giới hạn sử dụng 80% CPU
          memory: 1024M    # Giới hạn sử dụng 1GB RAM
        reservations:
          cpus: '0.1'      # Đảm bảo ít nhất 10% CPU
          memory: 256M     # Đảm bảo ít nhất 256MB RAM
    logging:
      driver: "json-file"
      options:
        max-size: "10m"    # Giới hạn kích thước mỗi file log
        max-file: "3"      # Số lượng file log tối đa được giữ lại
    volumes:
      - ../:/var/www/html
      - app_storage:/var/www/html/storage
      - app_cache:/var/www/html/bootstrap/cache
    networks:
      - corevsphim_network
    depends_on:
      - redis
    env_file:
      - .env.docker
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - LOG_LEVEL=error
      - LOG_DAYS=7
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Nginx Web Server
  webserver:
    image: nginx:1.21-alpine
    container_name: corevsphim_webserver
    restart: unless-stopped
    ports:
      - "${NGINX_PORT:-8080}:80"
    volumes:
      - ../:/var/www/html:ro
      - ./docker/nginx/:/etc/nginx/conf.d/:ro
    networks:
      - corevsphim_network
    depends_on:
      app:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

  # Redis (for caching and sessions)
  redis:
    image: redis:7.0-alpine
    container_name: corevsphim_redis
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
    command: >
      redis-server
      --appendonly yes
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --requirepass ${REDIS_PASSWORD:-redispassword}
    ports:
      - "${REDIS_PORT:-6380}:6379"
    volumes:
      - redis_data:/data
    networks:
      - corevsphim_network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # phpMyAdmin (Optional - for external database management)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: corevsphim_phpmyadmin
    restart: unless-stopped
    ports:
      - "${PHPMYADMIN_PORT:-8081}:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_ABSOLUTE_URI: "http://localhost:${PHPMYADMIN_PORT:-8081}/"
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT:-3306}
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 500M
      MEMORY_LIMIT: 512M
    networks:
      - corevsphim_network
    deploy:
      resources:
        limits:
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

networks:
  corevsphim_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  redis_data:
    driver: local
  app_storage:
    driver: local
  app_cache:
    driver: local
